# DO NOT EDIT THIS FILE!
#
# Python module calcApp__POA generated by omniidl

import omniORB
omniORB.updateModule("calcApp__POA")

# ** 1. Stub files contributing to this module
import calcApp_idl

# ** 2. Sub-modules

# ** 3. End
