# DO NOT EDIT THIS FILE!
#
# Python module calcApp generated by omniidl

import omniORB
omniORB.updateModule("calcApp")

# ** 1. Stub files contributing to this module
import calcApp_idl

# ** 2. Sub-modules

# ** 3. End
