package calcApp;


/**
* calcApp/calcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcApp.idl
* Domingo, 19 de Novembro de 2017 19h50min24s BRST
*/

public abstract class calcPOA extends org.omg.PortableServer.Servant
 implements calcApp.calcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("soma", new java.lang.Integer (0));
    _methods.put ("sub", new java.lang.Integer (1));
    _methods.put ("multi", new java.lang.Integer (2));
    _methods.put ("div", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calcApp/calc/soma
       {
         float n1 = in.read_float ();
         float n2 = in.read_float ();
         float $result = (float)0;
         $result = this.soma (n1, n2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // calcApp/calc/sub
       {
         float n1 = in.read_float ();
         float n2 = in.read_float ();
         float $result = (float)0;
         $result = this.sub (n1, n2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // calcApp/calc/multi
       {
         float n1 = in.read_float ();
         float n2 = in.read_float ();
         float $result = (float)0;
         $result = this.multi (n1, n2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // calcApp/calc/div
       {
         float n1 = in.read_float ();
         float n2 = in.read_float ();
         float $result = (float)0;
         $result = this.div (n1, n2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calcApp/calc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public calc _this() 
  {
    return calcHelper.narrow(
    super._this_object());
  }

  public calc _this(org.omg.CORBA.ORB orb) 
  {
    return calcHelper.narrow(
    super._this_object(orb));
  }


} // class calcPOA
