package calcApp;


/**
* calcApp/calcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcApp.idl
* Domingo, 19 de Novembro de 2017 19h50min24s BRST
*/

public interface calcOperations 
{
  float soma (float n1, float n2);
  float sub (float n1, float n2);
  float multi (float n1, float n2);
  float div (float n1, float n2);
} // interface calcOperations
