package calcApp;


/**
* calcApp/calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcApp.idl
* Domingo, 19 de Novembro de 2017 19h50min24s BRST
*/

public interface calc extends calcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc
