package calcApp;


/**
* calcApp/calcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcApp.idl
* Domingo, 19 de Novembro de 2017 19h50min24s BRST
*/

abstract public class calcHelper
{
  private static String  _id = "IDL:calcApp/calc:1.0";

  public static void insert (org.omg.CORBA.Any a, calcApp.calc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calcApp.calc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calcApp.calcHelper.id (), "calc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calcApp.calc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_calcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calcApp.calc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calcApp.calc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calcApp.calc)
      return (calcApp.calc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calcApp._calcStub stub = new calcApp._calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calcApp.calc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calcApp.calc)
      return (calcApp.calc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calcApp._calcStub stub = new calcApp._calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
