package calcApp;

/**
* calcApp/calcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcApp.idl
* Domingo, 19 de Novembro de 2017 19h50min24s BRST
*/

public final class calcHolder implements org.omg.CORBA.portable.Streamable
{
  public calcApp.calc value = null;

  public calcHolder ()
  {
  }

  public calcHolder (calcApp.calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calcApp.calcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calcApp.calcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calcApp.calcHelper.type ();
  }

}
